/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    MediaViewer: typeof import('./src/components/MediaViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunDrawer: typeof import('./src/components/RunDrawer.vue')['default']
    StageTimeline: typeof import('./src/components/StageTimeline.vue')['default']
    UAlert: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UIcon: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USelect: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlideover: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    USwitch: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.11.2_9aa696d93cfd7497fbce5d93d49505cb/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
